preset: laravel

enabled:
  - concat_with_spaces
  - align_double_arrow

disabled:
  - phpdoc_summary
  - concat_without_spaces
  - not_operator_with_successor_space
  - simplified_null_return

finder:
  not-name:
    - "_migration_helper.php"
