risky: false
version: 7
preset: laravel
enabled:
  - concat_with_spaces
  - align_double_arrow
disabled:
  - unused_use
  - phpdoc_summary
  - concat_without_spaces
  - not_operator_with_successor_space
finder:
  exclude:
    - "modules"
    - "node_modules"
    - "storage"
    - "vendor"
  name: "*.php"
  not-name:
    - "*.blade.php"
    - "_ide_helper.php"
    - "index.php"
    - "server.php"
