php:
  preset: laravel
  enabled:
    - concat_with_spaces
    - align_double_arrow
    - alpha_ordered_imports
  disabled:
    - length_ordered_imports
    - unused_use
    - phpdoc_summary
    - concat_without_spaces
    - not_operator_with_successor_space
    - simplified_null_return
    - phpdoc_to_comment
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
